### ISSUE TITLE
map<string,string> not producing results shown in example

### ISSUE THREAD

**Issue by ty-newton** [dvasilen/Hive-XML-SerDe#12]
Nice software.  Unfortunately I've run into a problem.
When I try the example from usage page (https://github.com/dvasilen/Hive-XML-SerDe/wiki/XML-data-sources) I get different results than what are shown.  Instead of the financial column showing
```
{"income": "18", "creddebt": "1.003392", "othdebt": "2.740608", "default": "0"}
```
It shows
```
{"financial":"<string><income>18</income><creddebt>1.003392</creddebt><othdebt>2.740608</othdebt><default>0</default></string>"}
```
The same happens for demographics.

I'm using the version from maven: hivexmlserde-1.0.5.2.jar
note: this is different to what is in GitHub repository: hivexmlserde-1.0.0.0.jar, pom.xml builds v1.0.0.0

Sadly for my real world use of the map<string,string> I get the same problem.  If this is expected functionality do you have an example of using the serde with the XML content in the financial column?

**Comment by dvasilen** [comment]
Please follow the approach shown in https://github.com/dvasilen/Hive-XML-SerDe/issues/8
and let me know if it did not help

**Comment by ty-newton** [comment]
Sorry about not looking in the closed issues.  Using the * solves it.

What's going on with the jar version being newer on Maven?

**Comment by dvasilen** [comment]
The latest version is on Maven... it is complied from this branch  "HIVE_6835_HIVE_8560":

https://github.com/dvasilen/Hive-XML-SerDe/tree/HIVE_6835_HIVE_8560

https://github.com/dvasilen/Hive-XML-SerDe/raw/HIVE_6835_HIVE_8560/release/hivexmlserde-1.0.5.2.jar
