### ISSUE TITLE
Record splitting with xml namespaces giving error

### ISSUE THREAD

**Issue by ty-newton** [dvasilen/Hive-XML-SerDe#13]
Hi,
I have the following XML document which I am trying to split so that I get a row for each repeat of the ReportingFI section.  Unfortunately I get an error from Hive which I have been unable to resolve.  Is there anything you can suggest?
```
<?xml version="1.0" encoding="UTF-8" ?>
<ftc:FATCA_OECD version="1"
  xmlns:ftc="urn:oecd:ties:fatca:v1"
  xmlns:sfa="urn:oecd:ties:stffatcatypes:v1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:oecd:ties:fatca:v1 FatcaXML_v1.1.xsd ">
  <ftc:MessageSpec>
    <sfa:MessageRefId>Sample1</sfa:MessageRefId>
  </ftc:MessageSpec>
  <ftc:FATCA>
    <ftc:ReportingFI>
      <sfa:Name>a</sfa:Name>
      <sfa:Name>b</sfa:Name>
      <ftc:DocSpec>
        <ftc:DocRefId>d1</ftc:DocRefId>
      </ftc:DocSpec>
    </ftc:ReportingFI>
    <ftc:ReportingFI>
      <sfa:Name>c</sfa:Name>
      <sfa:Name>d</sfa:Name>
      <ftc:DocSpec>
        <ftc:DocRefId>d2</ftc:DocRefId>
      </ftc:DocSpec>
    </ftc:ReportingFI>
  </ftc:FATCA>
</ftc:FATCA_OECD>
```
My overall objective is to get a table looking like this:
```
MessageRefId     |     DocRefId     |     Name
------------           --------           ----
Sample1                    d1             ["a","b"]
Sample1                    d2             ["c","d"]
```
My understanding is that to get the one row for each ReportingFI I need to set the table properties:
```
TBLPROPERTIES (
  "xmlinput.start"="<ftc:ReportingFI",
  "xmlinput.end"="</ftc:ReportingFI>"
);
```
Unfortunately I get this error which I haven't been able to resolve:
```
java.io.IOException: org.apache.hadoop.hive.serde2.SerDeException: java.lang.RuntimeException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 18; The prefix "ftc" for element "ftc:ReportingFI" is not bound.
```

Any suggestions?

Thanks

**Comment by dvasilen** [comment]
Please note that you are selecting the following XML fragment: 
```
<ftc:ReportingFI>
      <sfa:Name>c</sfa:Name>
      <sfa:Name>d</sfa:Name>
      <ftc:DocSpec>
        <ftc:DocRefId>d2</ftc:DocRefId>
      </ftc:DocSpec>
</ftc:ReportingFI>
```

This is invalid XML as your XML namespace prefixes cannot be resolved. The first step would be to get rid of XML namespaces. This can be done for example as an XSL transformation.  

Here is the python script you can use:

import sys
import lxml.etree as ET

dom = ET.parse(sys.argv[1])
xslt = ET.parse(sys.argv[2])
transform = ET.XSLT(xslt)
newdom = transform(dom)
print(ET.tostring(newdom, pretty_print=True))

The first parameter is the path to the XML file with namespaces.
The second parameter is the XSLT which looks like this:

```
<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:output method="xml" indent="yes" />

    <xsl:template match="*">
        <xsl:element name="{local-name(.)}">
            <xsl:apply-templates select="@* | node()" />
        </xsl:element>
    </xsl:template>
    <xsl:template match="@*">
        <xsl:attribute name="{local-name(.)}">
      <xsl:value-of select="." />
    </xsl:attribute>
    </xsl:template>
</xsl:stylesheet>
```

The output will look like this:
```
<FATCA_OECD version="1" schemaLocation="urn:oecd:ties:fatca:v1
FatcaXML_v1.1.xsd ">
  <MessageSpec>
    <MessageRefId>Sample1</MessageRefId>
  </MessageSpec>
  <FATCA>
    <ReportingFI>
      <Name>a</Name>
      <Name>b</Name>
      <DocSpec>
        <DocRefId>d1</DocRefId>
      </DocSpec>
    </ReportingFI>
    <ReportingFI>
      <Name>c</Name>
      <Name>d</Name>
      <DocSpec>
        <DocRefId>d2</DocRefId>
      </DocSpec>
    </ReportingFI>
  </FATCA>
</FATCA_OECD>
```
and your start/stop byte sequence will be 

```
TBLPROPERTIES (
  "xmlinput.start"="<ReportingFI>",
  "xmlinput.end"="</ReportingFI>"
);
```

Let me know if it did not work for you.

**Comment by dvasilen** [comment]
Also please keep in mind that if you have to have MessageRefId as well as elements from ReportingFI you should be selecting the root element of your XML:  
```
TBLPROPERTIES (
  "xmlinput.start"="<FATCA_OECD ",
  "xmlinput.end"="</FATCA_OECD>"
);
```
otherwise, if you just select ReportingFI element, as in your original example, the MessageRefId element will not be available for processing.

**Comment by ty-newton** [comment]
Thanks, I tried the removal of namespaces on a small piece of unrelated test data and it seems to work.

With respect to getting the MessageRefId into the table; I agree that limiting the scope of the xml serde means I can't reference it.

If I use the full document scope I'm not sure how to handle ReportingFI so I end up with each instance of it (i.e. the complex data contained therein) as independent items.  If I limit the scope each instance ends up in a row.  If I do an xpath from the root node I end up with data from all instances of ReportingFI.  Any suggestions?

**Comment by dvasilen** [comment]
Yes, it looks tricky. It should be [theoretically] possible to handle complex data like that in Hive but this particular XML schema design makes it difficult (if not impossible) to conveniently map it to a Hive row. For example, for the Name array in
```
<ReportingFI>
  <Name>a</Name>
  <Name>b</Name>
  <DocSpec>
    <DocRefId>d1</DocRefId>
  </DocSpec>
</ReportingFI>
```
I would normally expect to see a wrapper element (say, Names) like 
```
<ReportingFI>
  <Names>
    <Name>a</Name>
    <Name>b</Name>
  </Names>
  <DocSpec>
    <DocRefId>d1</DocRefId>
  </DocSpec>
</ReportingFI>
```
If we had that Names wrapper it would be possible to map that to the Hive array element as a part of the ReportingFI struct element .... but without this I do not see how it can be done.

Given the XML schema I would think that only some custom solution to flatten the XML (to say, CSV) will give you the expected results.

**Comment by dvasilen** [comment]
So for what it's worth....

Assuming that your XML looks like this (note the wrapper element for Names):
```
<FATCA_OECD version="1" schemaLocation="urn:oecd:ties:fatca:v1 FatcaXML_v1.1.xsd ">
  <MessageSpec>
    <MessageRefId>Sample1</MessageRefId>
  </MessageSpec>
  <FATCA>
    <ReportingFI>
     <Names>
      <Name>a</Name>
      <Name>b</Name>
     </Names>
      <DocSpec>
        <DocRefId>d1</DocRefId>
      </DocSpec>
    </ReportingFI>
    <ReportingFI>
     <Names>
      <Name>c</Name>
      <Name>d</Name>
     </Names>
      <DocSpec>
        <DocRefId>d2</DocRefId>
      </DocSpec>
    </ReportingFI>
  </FATCA>
</FATCA_OECD>
```
Your Hive table CREATE DDL could look like this:
```
DROP TABLE IF EXISTS fatca_modified;
CREATE TABLE fatca_modified(messagerefid string, 
reportingfis array<struct<reportingfi:struct<names:array<struct<name:string>>,docspec:struct<docrefid:string>>>>)
ROW FORMAT SERDE 'com.ibm.spss.hive.serde2.xml.XmlSerDe'
WITH SERDEPROPERTIES (
 "xml.processor.class"="com.ximpleware.hive.serde2.xml.vtd.XmlProcessor",
 "column.xpath.messagerefid"="/FATCA_OECD/MessageSpec/MessageRefId/text()",
 "column.xpath.reportingfis"="/FATCA_OECD/FATCA/ReportingFI"
)
STORED AS
     INPUTFORMAT 'com.ibm.spss.hive.serde2.xml.XmlInputFormat'
     OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat'
     TBLPROPERTIES (
     "xmlinput.start"="<FATCA_OECD ",
     "xmlinput.end"="</FATCA_OECD>"
     );

load data local inpath '/home/dvasilen/Misc/HIVE/XML/fatca_modified.xml' OVERWRITE into table fatca_modified;

select * from fatca_modified;
```
So to get the expected results you will use SELECT statement like this:

```
set hive.exec.mode.local.auto=true;
set hive.cli.print.header=true;

SELECT messagerefid, 
exp_reportingfi.reportingfi.docspec.docrefid,
exp_reportingfi.reportingfi.names
FROM fatca_modified
LATERAL VIEW explode(reportingfis) exploded_reportingfis AS exp_reportingfi;
```

And here is the output:
```
messagerefid	docrefid	names
Sample1	d1	[{"name":"a"},{"name":"b"}]
Sample1	d2	[{"name":"c"},{"name":"d"}]
Time taken: 7.724 seconds, Fetched: 2 row(s)
```

**Comment by ty-newton** [comment]
Thanks.  I appreciate the advice and example.

**Comment by shreyas080** [comment]
Hi,
The above solution provided is giving the com/ximpleware/XPathParseException.  Can you please guide on what might be the issue.
Thanks in advance

**Comment by whitsonk** [comment]
The python script and the XLST you provided were super helpful. 
Thank You!

**Comment by davoscollective** [comment]
array<struct<reportingfi:struct<names:array<struct<name:string>>,docspec:struct<docrefid:string>>>>

This example syntax really helped me.  I guess it makes sense that reportingfis  is an array of struct, but when to name the nested types is not immediately obvious. I guess this is Hive syntax, and not related to this SerDe, but I can't find a good reference for it.

**Comment by KarthikeyanRamamurthy** [comment]
Hi, I have a similar case now, where XML has a namespace prefix in the tags. I am wondering is there any option to indicate the XMLSERDE to use the namespace like Oracle (oxh-namespace.prefix). Would appreciate your suggestions. TIA. Karthik
