### ISSUE TITLE
Parsing the repeated tag files

### ISSUE THREAD

**Issue by jindalcastle** [dvasilen/Hive-XML-SerDe#14]
Hi,

I am not able to parse xml if tags are repeating with multiple inner tags. I just started using this serde jar file. It would be nice if you can help me out with that.

```
<abc>
    <def>
      <ghi> 123 </ghi>
      <jkl>123</jkl>
   </def>
   <def>
      <ghi>456</ghi>
      <jkl>123</jkl>
   </def>  
 </abc>
```
I am not able to parse this as def tag is repeating and when i try to retrieve the value of ghi and jkl with serde. it gives me the value but it loose the relation between the tag values
  
Thanks,
Piyush jindal

**Comment by dvasilen** [comment]
Please let me know how your CREATE TABLE statement looks like and what output you expect to see from SELECT * FROM... query.

**Comment by hunraid** [comment]
Hi, I think I have a similar problem with parsing an xml without losing relation between some of the tags. 
  ```
<students>
<student> 
<name><fname>john</fname><lname>nash</lname></name>
<age>21</age>
</student>
<student>
<name><fname>Eliza</fname><lname>sanders</lname></name>
<age>23</age>
</student>
<student1>
<name>Kevin</name>
<age>31</age>
</student1>
<student1>
<name>Sam </name>
<age>33</age>
</student1>
</students>
