### ISSUE TITLE
Namespace processing

### ISSUE THREAD

**Issue by sirhallt** [dvasilen/Hive-XML-SerDe#15]
Hi, thank you for this tool it is of great use for our use case.  We have the following XML:
<CODE>
<PRE>&lt;TestResults uuid="1283BCE8-AB34-AE34-FA39-123456789012" xmlns="urn:IEEE-1636.1:2013:TestResults" xmlns:c="urn:IEEE-1671:2010:Common" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:sc="urn:IEEE-1636.99:2013:SimicaCommon" version="6.02" xsi:schemaLocation="urn:IEEE-1636.1:2013:TestResults TestResults.xsd">
  &lt;ResultSet ID="0" name="HC" startDateTime="2015-04-17T3:19:11-06:00" endDateTime="2015-04-17T3:38:16-06:00">
    &lt;TestGroup ID="Unpowered_Tests" name="Unpowered Tasks" startDateTime="2015-04-17T3:30:53-06:00"  endDateTime="2015-04-17T3:38:15-06:00">
      &lt;TestGroup ID="Resistor_ID_Test_3" name="Resistor ID Test" startDateTime="2015-04-17T3:31:51-06:00"  endDateTime="2015-04-17T3:31:54-06:00">
         &lt;Test ID="Resistor_ID_S1_Test" name="Resistor ID S1 Test" startDateTime="2015-04-17T3:31:51-06:00" endDateTime="2015-04-17T3:31:52-06:00">
           &lt;Outcome value="Failed" />
           &lt;TestData>
           &lt;c:Datum d4p1:type="c:double" standardUnit="Ohm" value="9.46057E+009" xmlns:d4p1="http://www.w3.org/2001/XMLSchema-instance" xmlns:c="urn:IEEE-1671:2010:Common" />
           &lt;/TestData>
         &lt;/Test>
        &lt;/TestGroup>
        &lt;Outcome value="Failed" />
    &lt;/TestGroup>
  &lt;/ResultSet>
 &lt;/TestResults>
</PRE>
</CODE>

I am trying to define the c:Datum value attribute as a column in a table, but it continues to be NULL.  How would I reference that value in a column?  Here is what I have now:

<CODE>
<PRE>
CREATE TABLE xml_atml(test_name STRING, data_value STRING)
ROW FORMAT SERDE 'com.ibm.spss.hive.serde2.xml.XmlSerDe'
WITH SERDEPROPERTIES (
"column.xpath.test_name"="//Test/@name",
"column.xpath.data_value"="//Test/TestData/*[local-name(.)='Datum']/@value"
)
STORED AS
INPUTFORMAT 'com.ibm.spss.hive.serde2.xml.XmlInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat'
LOCATION '/user/hdfs/ATML'
TBLPROPERTIES (
"xmlinput.start"="&lt;Test ID",
"xmlinput.end"="&lt;/Test>"
);
</PRE>
</CODE>

**Comment by dvasilen** [comment]
The XPath and table CREATE DDL look fine to me. I will take a closer look at this issue later today.  You might want to also consider getting rid of the XML namespaces before uploading the files to HDFS. See Issue #13 for an example.

**Comment by dvasilen** [comment]
I tried that XML on my environment (Hadoop 2.6, Hive 1.2.0, hivexmlserde-1.5.0.3.jar) and it seems to be working:

```
hive> DROP TABLE IF EXISTS sirhallt;
OK
Time taken: 1.051 seconds
hive> 
    > CREATE TABLE sirhallt(test_name STRING, data_value STRING)
    > ROW FORMAT SERDE 'com.ibm.spss.hive.serde2.xml.XmlSerDe'
    > WITH SERDEPROPERTIES (
    > "column.xpath.test_name"="//Test/@name",
    > "column.xpath.data_value"="//Test/TestData/*[local-name(.)='Datum']/@value"
    > )
    > STORED AS
    > INPUTFORMAT 'com.ibm.spss.hive.serde2.xml.XmlInputFormat'
    > OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat'
    > TBLPROPERTIES (
    > "xmlinput.start"="<Test ID",
    > "xmlinput.end"="</Test>"
    > );
OK
Time taken: 1.742 seconds
hive> 
    > load data local inpath '/home/dvasilen/Misc/HIVE/XML/sirhallt.xml' OVERWRITE into table sirhallt;
Loading data to table default.sirhallt
Table default.sirhallt stats: [numFiles=1, numRows=0, totalSize=1246, rawDataSize=0]
OK
Time taken: 1.651 seconds
hive> 
    > select * from sirhallt;
OK
Resistor ID S1 Test	9.46057E+009
Time taken: 0.605 seconds, Fetched: 1 row(s)
hive> 
```

**Comment by sirhallt** [comment]
I realized that in my XML there was an additional parent node I didn't have in my exmplae adding that to my xPath corrected the issue.  Thank you for your quick reponse and assistance!
