### ISSUE TITLE
Complex objects with multiple lists at same level

### ISSUE THREAD

**Issue by cartral** [dvasilen/Hive-XML-SerDe#16]
Hi,
I am trying to expose complex xml using your serde.

One problem scenario arises when an xml element contains two child lists, e.g.

```xml
<mr7>
	<b>testb1</b>
	<b>testb2</b>
	<c>testc</c>
	<c>testd</c>
</mr7>
```
(In more realistic use cases, the children could themselves be objects and lists etc etc)

The issue here is that the serde seems to map all child lists to a single array of structs with the child lists represented as fields within this struct. There are some issues with this mapping (e.g. individual child array lengths are lost - instead we have an array of structs of size sum(#child lists).

i.e.
```sql
CREATE EXTERNAL TABLE mr7_table(
mr7  STRUCT <
  mr7: ARRAY <
     STRUCT <
      b:                                 STRING,
      c:                                 STRING
     >
  >
>
) ROW FORMAT SERDE 'com.ibm.spss.hive.serde2.xml.XmlSerDe'
WITH SERDEPROPERTIES (
  "column.xpath.mr7"="mr7"
)
STORED AS
  INPUTFORMAT 'com.ibm.spss.hive.serde2.xml.XmlInputFormat'
  OUTPUTFORMAT 

'org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat'
  LOCATION '/user/cloudera/mr7'
  TBLPROPERTIES (
    "xmlinput.start"="<mr7",
    "xmlinput.end"="</mr7>"
  );
```

Using our original XML, a select illustrates the problem:

```sql
select * from mr7_table
``` 
This results in mr7.b containg "testb1", "testb2", null, null and mr7.c containing null, null, "testc", testd".

i.e.
```
{"mr7":[{"b":"testb1","c":null},{"b":"testb2","c":null},{"b":null,"c":"testc"},{"b":null,"c":"testd"}]}
```

Is there an alternative way of doing this / without falling to map / that results in a natural array mapping / where sizes are preserved?

Thanks,

Michael

**Comment by dvasilen** [comment]
Given the implementation the only way to represent the elements "b" and "c" as arrays is to introduce array wrappers. I think it was briefly discussed in issue #13. 
```
<mr7>
    <b_array>
      <b>testb1</b>
      <b>testb2</b>
    </b_array>
    <c_array>
      <c>testc1</c>
      <c>testc2</c>
    </c_array>
</mr7>
```

**Comment by cartral** [comment]
Thanks for the quick response!

Unfortunately, the XML is not something I can change for my use case.
To compound matters, these files have pretty complex records and child lists often occur multiple times and at different levels within the same record - so the column solution won't work :-(

I guess one solution to this would be to modify the *hive* mapping, i.e. to add the array wrapper to the hive side rather than the xml side (perhaps as a configurable option). I will try to take a look at the source - though I'll admit I am new to SerDe development.

Aside: The complexity of the files we are processing is such that schema-on-read may prove inappropriate. Consequently, we may end up copying the data (when flattening the structure). However, we had hoped to have an external table for the original file-set in all scenarios (a "live" view of the source).

**Comment by dvasilen** [comment]
>>>> I will try to take a look at the source - though I'll admit I am new to SerDe development.

If you plan to fork the repository I suggest using the "HIVE_1.2_HADOOP_2.6_COMP-1.5.0.3" branch as a starting point. The branch contains the latest code for the SerDe.

**Comment by dvasilen** [comment]
Closed as "functions as designed".
