### ISSUE TITLE
 Can not convert #STRING to a NodeList!

### ISSUE THREAD

**Issue by TejaswiniChillara** [dvasilen/Hive-XML-SerDe#18]
Throws this error when i trying to parse the xml file 

org.apache.hadoop.hive.serde2.SerDeException: java.lang.RuntimeException: javax.xml.xpath.XPathExpressionException: com.sun.org.apache.xpath.internal.XPathException: Can not convert #STRING to a NodeList!

**Comment by dvasilen** [comment]
How does your XML and CREATE TABLE statement look like?

**Comment by dvasilen** [comment]
I did not receive requested information from the submitter. Closing this issue as "Cannot replicate".
