### ISSUE TITLE
NULL value returned while trying to read Map element during Hive Deserilisation

### ISSUE THREAD

**Issue by rkpadhi2050** [dvasilen/Hive-XML-SerDe#21]
@dvasilen 

Suppose I have the following XML data:
&Record&
    &Data&
               &Attribute name ="Ashok" value "hjkiuy+hj/uo" /&
               &Attribute name ="Raja" value "klopluy+tgbvf/uo"/&
    &/Data&
&/Record&

CREATE EXTERNAL TABLE ABC
(
ATTRIBUTE MAP<STRING, STRING>
)
ROW FORMAT SERDE 'com.ibm.spss.hive.serde2.xml.XmlSerDe'
WITH SERDEPROPERTIES ( 
  "column.xpath.ATTRIBUTE"="/Record/Data",
  "xml.map.specification.entry"="@name->@value"
STORED AS
INPUTFORMAT 'com.ibm.spss.hive.serde2.xml.XmlInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat'
TBLPROPERTIES (
  "xmlinput.start"="<Record",
  "xmlinput.end"="/Record>"
);

SELECT ATTRIBUTE["value"] from ABC;
Note: I replaced tag with & as with that the post i am not able to post.
It returns NULL value. Please suggest.

**Comment by rkpadhi2050** [comment]
Deserilisation itself not working properly. 

{"result":"<string><Attribue name=\"rama\" value=\"adhj/k\"/><Attribue name=\"hari\" value=\"kili+j/k\"/></string>"}

Please help.

**Comment by rkpadhi2050** [comment]
This example is as per 4.3) Attribute to Attribute

Just noticed derserilisation result is also not coming.

{"result":"string Attribue name=\"Ashok\" value=\"hjkiuy+hj/uo\"/ Attribue name=\"Raja\" value=\"klopluy+tgbvf/uo"//string"}

Not mentioning <> in result as result is not displayed here if I include </>

Please help.

**Comment by rkpadhi2050** [comment]
Sorry to trouble you. It is working fine. There is problem in my code. so closing this issue.

**Comment by dvasilen** [comment]
Thanks, I am glad it worked for you.
