### ISSUE TITLE
Timestamp DataType are not getting deserialized in XML

### ISSUE THREAD

**Issue by rkpadhi2050** [dvasilen/Hive-XML-SerDe#22]
if we define TIMESTAMP data type. Then while querying in HIVE table it returns NULL. 

NOTE: if i give STRING data type for intended TIMESTAMP data then it returns value. But it is always wise to define TIMESTAMP data type for the kind of data.

Please help

**Comment by rkpadhi2050** [comment]
Similar issues were raised in Hive-JSON-Serde. This is just for your reference.

https://github.com/rcongiu/Hive-JSON-Serde/issues/91

**Comment by dvasilen** [comment]
Thanks for raising this issue. At this point we do not have plans to fix that but we could consider this for the next release.

**Comment by rkpadhi2050** [comment]
Thank you for reply. I am waiting for the next release.

**Comment by rkpadhi2050** [comment]
@dvasilen  any time line when we will get next release including this fix. sorry to rush you.

**Comment by dvasilen** [comment]
I am afraid we do not have a timeline for the next release at this point. But please feel free to fork the repository and make the changes as needed. Please use HIVE_1.2_HADOOP_2.6_COMP-1.5.0.3 branch as a starting point as it is the latest. If you need that urgently you can consider getting a string value and then using [Hive Date UDFs](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+UDF) to convert to timestamp.

**Comment by dvasilen** [comment]
Closed as no plans to fix.
