### ISSUE TITLE
Error While parsing XML

### ISSUE THREAD

**Issue by sspechetti** [dvasilen/Hive-XML-SerDe#27]
I am trying to load xml data into hive in Microsoft azure. I have a case where there are multiple child nodes with same tag name.

For reference : I pasted my xml here : http://pastebin.com/v1ZfF37z

I tried following your solution to the issue "Parent to nested child relationship #10" , but I m getting multiple errors.

Here is the code : 

```
ADD JAR wasb:///user/hivexmlserde-1.0.5.3.jar;

SET mapred.input.dir.recursive=true;
SET hive.mapred.supports.subdirectories=true;
DROP TABLE IF EXISTS losApplicantEmployer;
CREATE EXTERNAL TABLE losApplicantEmployer (  

	ApplicantID string,
	ApplicantType string,
	Emp_id array<string>,
	Emp_Type array<string>,
	Emp_Name array<string>,
	YearsEmployed array<int>,
	MonthsEmployed array<int>,
	CreateDate array<string>,
	UpdateDate array<string>
  
  )
ROW FORMAT SERDE 
  'com.ibm.spss.hive.serde2.xml.XmlSerDe' 

WITH SERDEPROPERTIES(

		"xml.processor.class"="com.ximpleware.hive.serde2.xml.vtd.XmlProcessor",
		"column.xpath.ApplicantID" = "/LoanApplications/LoanApplication[@deal_type='REQUESTED']/LoanApplicationStates/LoanApplicationState/Customers/Customer/@customer_id",
		"column.xpath.ApplicantType" = "/LoanApplications/LoanApplication[@deal_type='REQUESTED']/LoanApplicationStates/LoanApplicationState/Customers/Customer/@type",
		"column.xpath.Emp_id" = "/LoanApplications/LoanApplication[@deal_type='REQUESTED' or 'RECOMMENDED']/LoanApplicationStates/LoanApplicationState/Customers/Customer/Employers/Employer/@employer_id",
		"column.xpath.Emp_Type" = "/LoanApplications/LoanApplication[@deal_type='REQUESTED' or 'RECOMMENDED']/LoanApplicationStates/LoanApplicationState/Customers/Customer/Employers/Employer/@type_code",
		"column.xpath.Emp_Name" = "/LoanApplications/LoanApplication[@deal_type='REQUESTED' or 'RECOMMENDED']/LoanApplicationStates/LoanApplicationState/Customers/Customer/Employers/Employer/@employer_name",
		"column.xpath.YearsEmployed" = "/LoanApplications/LoanApplication[@deal_type='REQUESTED' or 'RECOMMENDED']/LoanApplicationStates/LoanApplicationState/Customers/Customer/Employers/Employer/@years_employed",
		"column.xpath.MonthsEmployed" = "/LoanApplications/LoanApplication[@deal_type='REQUESTED' or 'RECOMMENDED']/LoanApplicationStates/LoanApplicationState/Customers/Customer/Employers/Employer/@months_employed",
		"column.xpath.CreateDate" = "/LoanApplications/LoanApplication[@deal_type='REQUESTED' or 'RECOMMENDED']/LoanApplicationStates/LoanApplicationState/Customers/Customer/Employers/Employer/@create_date",
		"column.xpath.UpdateDate" = "/LoanApplications/LoanApplication[@deal_type='REQUESTED' or 'RECOMMENDED']/LoanApplicationStates/LoanApplicationState/Customers/Customer/Employers/Employer/@update_date"     
		 )  
		 
STORED AS INPUTFORMAT 
  'com.ibm.spss.hive.serde2.xml.XmlInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'

LOCATION'wasb://glshadoopd3@glsllcteststorage1.blob.core.windows.net/Safe/2016/05/12'


TBLPROPERTIES ("xmlinput.start"="<LoanApplications xmlns","xmlinput.end"="</LoanApplications>" );  

create table table2 as
select ApplicantID, ApplicantType, array_index(Emp_id, n) as id, array_index(Emp_Type, n) as type, array_index(Emp_Name, n) as ename, array_index(YearsEmployed, n) as yrs, 
array_index(MonthsEmployed, n) as mons, array_index(CreateDate, n) as cdate, array_index(UpdateDate, n) as ud
from  losApplicantEmployer lateral view numeric_range(size(Emp_id)) n1 as n;

select * from table2

```

The error I get is :

FAILED: SemanticException 10:68 AS clause has an invalid number of aliases. Error encountered near token 'n1'

**Comment by sspechetti** [comment]
For reference : I pasted my xml here : http://pastebin.com/v1ZfF37z

**Comment by dvasilen** [comment]
Are you getting correct results when you run "select * from losApplicantEmployer"?

**Comment by sspechetti** [comment]
No I get an error there to. Do I need to add the brickhouse udfs ?

**Comment by dvasilen** [comment]
Yes, if you plan to use Brickhouse UDFs (such as array_index) you will have to add them.

**Comment by sspechetti** [comment]
By the way I am getting correct results for : select * from losApplicantEmployer

**Comment by sspechetti** [comment]
250163	PB	["369422","369423","369420","369421"]	["CURRENT","PREVIOUS","CURRENT","PREVIOUS"]	["81049&2016040715500693820","81049&2016040715500693820"]	[4,4]	[0,0]	["2016-05-12T08:38:46.0000000","2016-05-12T08:38:46.0000000","2016-05-12T08:38:46.0000000","2016-05-12T08:38:46.0000000"]	["2016-05-12T08:44:56.6330000","2016-05-12T08:44:56.6330000","2016-05-12T08:44:56.8530000","2016-05-12T08:38:49.0000000"]

**Comment by sspechetti** [comment]
While compiling do I need to keep the Jar name same as the filename ?

Error : 
Added [D:\Users\hdp\AppData\Local\Temp\9a1665c2-c998-4dfe-8e7a-9a9eadde9841_resources\ManuUDF.jar] to class path
Added resources: [wasb:///user/ManuUDF.jar]
FAILED: Class brickhouse.udf.collect.NumericRange not found
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.FunctionTask

**Comment by sspechetti** [comment]
This query gives me huge number of duplicates :
select ApplicantID, ApplicantType, Exp_Emp_id, Exp_Emp_Type, Exp_Emp_Name, Exp_YearsEmployed, Exp_MonthsEmployed, Exp_CreateDate, Exp_UpdateDate from losApplicantEmployer
LATERAL VIEW explode(Emp_id) myTable1 AS Exp_Emp_id
LATERAL VIEW explode(Emp_Type) myTable1 AS Exp_Emp_Type
LATERAL VIEW explode(Emp_Name) myTable1 AS Exp_Emp_Name
LATERAL VIEW explode(YearsEmployed) myTable1 AS Exp_YearsEmployed
LATERAL VIEW explode(MonthsEmployed) myTable1 AS Exp_MonthsEmployed
LATERAL VIEW explode(CreateDate) myTable1 AS Exp_CreateDate
LATERAL VIEW explode(UpdateDate) myTable1 AS Exp_UpdateDate;

**Comment by sspechetti** [comment]
The Result I want is 

250163  PB 369422  CURRENT 81049&2016040715500693820 4  0  2016-05-12T08:38:46.0000000  2016-05-12T08:44:56.6330000

250163  PB 369423  PREVIOUS   null                                       null null  2016-05-12T08:38:46.0000000
2016-05-12T08:44:56.6330000

**Comment by dvasilen** [comment]
As you are getting the correct results for the main table then I think the question is more about how to use Hive to flatten your data. I suggest to post the question to the user@hive.apache.org.

**Comment by sspechetti** [comment]
I figured it out. Thanks dvasilen. You may close the issue

**Comment by paciferous** [comment]
Could you please post the solution for the above issue? I have also run into the same issue and not able to figure out a way to fix it. Thank you.
