### ISSUE TITLE
How to handle this type of XML

### ISSUE THREAD

**Issue by rkpadhi2050** [dvasilen/Hive-XML-SerDe#28]
I have below type of XML. Please give me some idea to handle

![sample](https://cloud.githubusercontent.com/assets/17885317/15403016/caf4ddbe-1dee-11e6-8497-3add9d0a2804.jpg)

**Comment by dvasilen** [comment]
Please take a look at 
https://github.com/dvasilen/Hive-XML-SerDe/wiki/XML-data-sources
and 
http://www.enggjournals.com/ijcse/doc/IJCSE14-06-09-012.pdf

**Comment by rkpadhi2050** [comment]
Hi.. I did not see such type of XML in the link. it neither comes in Map  or Array. Please suggest. Sorry for asking may be simple question. Many thanks in advance.

**Comment by dvasilen** [comment]
Each employee record in the Hive table should be a map of string to string. You can access values using employee["Name"] and employee["Dept"].
