### ISSUE TITLE
XPath: Unable to get correct results

### ISSUE THREAD

**Issue by syedaliammar** [dvasilen/Hive-XML-SerDe#29]
Hi,
With an XML like the following, if I do //@AMOUNT, my Hive table gives me the result in only one row like this: <string>123.40567.80<string>

Also, the following gives me NULL as result:
//ammar:Series/ammar:Obs/@AMOUNT

So basically two questions: 

1. How do I project my one line result into separate rows?
2. Why is //ammar:Series/ammar:Obs/@AMOUNT returing a NULL?

`<CompactData><ammar:DataSet EXTRACTION_TIME="2014-06-30T00:00:00"><ammar:SEC_ID_GROUP IDENTIFIER_TYPE="BISON"></ammar:SEC_ID_GROUP><ammar:Series IDENTIFIER="1"><ammar:Obs AMOUNT="123.40"></ammar:Obs></ammar:Series><ammar:Series IDENTIFIER="1"><ammar:Obs AMOUNT="567.80"></ammar:Obs></ammar:Series></ammar:DataSet></CompactData>`

**Comment by dvasilen** [comment]
As a first step I suggest to get rid of XML namespaces. See #13 . Please also provide the complete XML and table CREATE DLL.

**Comment by dvasilen** [comment]
The submitter did not provide the complete XML and table CREATE DLL. Closing the issue as functions as designed.
