### ISSUE TITLE
Not able iterate through each struct elements in XML

### ISSUE THREAD

**Issue by swapnilpatil1682** [dvasilen/Hive-XML-SerDe#30]
Hello ,
I am trying to iterate through elements mentioned in Struct 
e.g. struct  < name:string,result:string, marks:int, age:int >  from XML. (I want to access each element in that struct one by one) 
How can I do that ? May I know "column.xpath.result" syntax for that to iterate through each element? 
OR Do I need to use other Data type like struct ?

**Comment by dvasilen** [comment]
I am not entirely sure I understand the question. Please open a separate issue and provide some simple XML example and the desired  Hive table schema.
