### ISSUE TITLE
How do you get the n-th element name?

### ISSUE THREAD

**Issue by whitsonk** [dvasilen/Hive-XML-SerDe#34]
Assuming you start with this...
`   <message>`
`      <foo>1</foo>`
`      <bar>2</bar>`
`      <baz>3</baz>`
`   </message>`

...and you create a field in a table that selects the 2nd element.
`CREATE EXTERNAL TABLE testXML(type string)`
`     ROW FORMAT SERDE 'com.ibm.spss.hive.serde2.xml.XmlSerDe'`
`     WITH SERDEPROPERTIES ("column.xpath.type"="/message/*[position()=2]")`
`     STORED AS`
`     INPUTFORMAT 'com.ibm.spss.hive.serde2.xml.XmlInputFormat'`
`     OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat'`
`     LOCATION '/tmp/messages/'`
`     TBLPROPERTIES (`
`     "xmlinput.start"="<message>",`
`     "xmlinput.end"="</message>"`
`     );`

The following query returns the 2nd node
`select * from testXML;`
`OK`
**`<bar>2</bar>`**
`Time taken: 0.175 seconds, Fetched: 1 row(s)`

However, what I really need to know is the name of the second node.
i.e. I need the following result.
`select * from testXML;`
**`bar`**

I tried several approaches without success including the following...
`"column.xpath.type"="name(/message/*[position()=2]/.)"`
`"column.xpath.type"="name(/message/*[position()=2])"`
`"column.xpath.type"="/message/*[position()=2]/name()"`

Thanks
Kevin

**Comment by dvasilen** [comment]
Your xpath ^^^ looks fine to me. I have also tried 

```
hive> DROP TABLE IF EXISTS xml_34;
OK
Time taken: 0.056 seconds
hive> 
    > CREATE  TABLE xml_34(t string)
    > ROW FORMAT SERDE 'com.ibm.spss.hive.serde2.xml.XmlSerDe'
    > WITH SERDEPROPERTIES ( "column.xpath.t"="name(/message/child::*[2])")
    > STORED AS
    > INPUTFORMAT 'com.ibm.spss.hive.serde2.xml.XmlInputFormat'
    > OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat'
    > TBLPROPERTIES (
    > "xmlinput.start"="<message>",
    > "xmlinput.end"="</message>"
    > );
OK
Time taken: 0.06 seconds
hive> 
    > load data local inpath '/Users/dvasilen/Misc/XML/34.xml' OVERWRITE into table xml_34;
Loading data to table default.xml_34
OK
Time taken: 0.13 seconds
hive> 
    > select * from xml_34;
OK
Failed with exception java.io.IOException:org.apache.hadoop.hive.serde2.SerDeException: java.lang.RuntimeException: javax.xml.xpath.XPathExpressionException: com.sun.org.apache.xpath.internal.XPathException: Can not convert #STRING to a NodeList!
Time taken: 0.08 seconds
hive> 
```
but that does not work either. I think serde expects the NodeList in this context. I do not see a simple way to workaround this.
