### ISSUE TITLE
Parsing Array of Structs

### ISSUE THREAD

**Issue by meetsriharsha** [dvasilen/Hive-XML-SerDe#38]
I am trying to load the following XML file using this serde.

```
<CustomerOrders>
  <Customers>
    <CustID>ALFKI</CustID>
    <Orders>
      <OrderID>10643</OrderID>
      <CustomerID>ALFKI</CustomerID>
      <OrderDate>1997-08-25</OrderDate>
    </Orders>
    <Orders>
      <OrderID>10692</OrderID>
      <CustomerID>ALFKI</CustomerID>
      <OrderDate>1997-10-03</OrderDate>
    </Orders>
    <CompanyName>Alfreds Futterkiste</CompanyName>
  </Customers>
  <Customers>
    <CustID>ANATR</CustID>
    <Orders>
      <OrderID>10308</OrderID>
      <CustomerID>ANATR</CustomerID>
      <OrderDate>1996-09-18</OrderDate>
    </Orders>
    <CompanyName>Ana Trujillo Emparedados y helados</CompanyName>
  </Customers>
</CustomerOrders>
```
My Hive `CREATE TABLE` query is:

```
CREATE TABLE CUSTOMERORDERS(
          CustID STRING,
          Orders ARRAY<STRUCT<OrderID:BIGINT,CustomerID:STRING,OrderDate:STRING>>,
          CompanyName STRING)
          ROW FORMAT SERDE 'com.ibm.spss.hive.serde2.xml.XmlSerDe'
          WITH SERDEPROPERTIES (
          "xml.processor.class"="com.ximpleware.hive.serde2.xml.vtd.XmlProcessor",
          "column.xpath.CustID"="/Customers/CustID/text()",
          "column.xpath.Orders"="/Customers/Orders",
          "column.xpath.ORDERID"="/Customers/Orders/OrderID/text()",
          "column.xpath.CUSTOMERID"="/Customers/Orders/CustomerID/text()",
          "column.xpath.ORDERDATE"="/Customers/Orders/OrderDate/text()",
          "column.xpath.CompanyName"="/Customers/CompanyName/text()")
          STORED AS INPUTFORMAT 'com.ibm.spss.hive.serde2.xml.XmlInputFormat'
          OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat'
          TBLPROPERTIES ("xmlinput.start"="<Customers>","xmlinput.end"= "</Customers>");
```

The output I am getting is:

```
hive> LOAD DATA INPATH 'hdfs:///user/hdfs/customerorders.xml' INTO TABLE CUSTOMERORDERS;
Loading data to table default.customerorders
Table default.customerorders stats: [numFiles=1, totalSize=669]
OK
Time taken: 0.097 seconds
hive> select * from customerorders;
OK
ALFKI   [{"orderid":null,"customerid":null,"orderdate":null},{"orderid":null,"customerid":null,"orderdate":null}]       Alfreds Futterkiste
ANATR   [{"orderid":null,"customerid":null,"orderdate":null}]   Ana Trujillo Emparedados y helados
Time taken: 0.039 seconds, Fetched: 2 row(s)
```

`OrderID`, `CustomerID`, `OrderDate `fields are being populated as `null`. Where could be the problem?

Thanks

**Comment by jamessonglin** [comment]
Try change below SERDEPROPERTIES lines:
          "column.xpath.Orders"="/Customers/Orders",
          "column.xpath.ORDERID"="/Customers/Orders/OrderID/text()",
          "column.xpath.CUSTOMERID"="/Customers/Orders/CustomerID/text()",
          "column.xpath.ORDERDATE"="/Customers/Orders/OrderDate/text()",

to only one line
 "column.xpath.Orders"="/Customers/Orders/*",

**Comment by meetsriharsha** [comment]
Thank you for the update.
I tried it. Used `"column.xpath.Orders"="/Customers/Orders/*"`, and removed the sub-tags of `Orders`.
The output is as below... This is not the required output.
Can you please give me more insights?

Thanks
```
hive> select * from customerorders;
OK
ALFKI   [{"orderid":"10643","customerid":null,"orderdate":null},{"orderid":null,"customerid":"ALFKI","orderdate":null},{"orderid":null,"customerid":null,"orderdate":"1997-08-25"},{"orderid":"10692","customerid":null,"orderdate":null},{"orderid":null,"customerid":"ALFKI","orderdate":null},{"orderid":null,"customerid":null,"orderdate":"1997-10-03"}]   Alfreds Futterkiste
ANATR   [{"orderid":"10308","customerid":null,"orderdate":null},{"orderid":null,"customerid":"ANATR","orderdate":null},{"orderid":null,"customerid":null,"orderdate":"1996-09-18"}]     Ana Trujillo Emparedados y helados
Time taken: 0.035 seconds, Fetched: 2 row(s)
```

**Comment by jlsalazar** [comment]
i have the same problem :(

**Comment by jlsalazar** [comment]
Did you manage to solve it?

**Comment by meetsriharsha** [comment]
I found a workaround here. Though the output is not exactly as I wanted, it's still convincing...
https://stackoverflow.com/questions/44180993/loading-nested-xml-data-into-hive-using-serde/44195499#44195499
So, I changed to Spark-XML framework which is more flexible.
Hope it helps

**Comment by jamessonglin** [comment]
This xml serde looks only work for one level xml parse and doesn't support nested structure.

So I end up with convert xml to json in Nifi using stylesheet, then ingest json into hdfs and create hive table using json serde.

**Comment by debuggerrr** [comment]
I think what @jamessonglin  is saying might be true because i am also facing the same problem.

**Comment by HARISHTULASI** [comment]
@jamessonglin  Were you able to convert the complex nested XML to JSON????? 

a) Did you create a flat file??
b) Did u split XML and create smaller chuncks??

**Comment by jamessonglin** [comment]
We use style sheet convert xml to json, it can completely covert any xml to
json.  And also be able to consistently convert dynamic xml element into
json array no matter it only has one or multiple repeat.
