### ISSUE TITLE
data not loading from xml file into hive table while using hive-xml-SerDe

### ISSUE THREAD

**Issue by ritikam2** [dvasilen/Hive-XML-SerDe#41]
Hi,
     I have following XML

```
<?xml version="1.0" encoding="ISO-8859-1"?>
<file-format>
<meta-header xfer="1.2.840.10008.1.2.1" name="Little Endian Explicit">
<element tag="0002,0000" vr="UL" vm="1" len="4" name="FileMetaInformationGroupLength">230</element>
<element tag="0002,0001" vr="OB" vm="1" len="2" name="FileMetaInformationVersion" binary="hidden"></element>
<element tag="0002,0002" vr="UI" vm="1" len="26" name="MediaStorageSOPClassUID">1.2.840.10008.5.1.4.1.1.4</element>
<element tag="0002,0003" vr="UI" vm="1" len="64" name="MediaStorageSOPInstanceUID">1.2.826.0.1.3680043.8.1055.1.20111103111148288.81713267.86905863</element>
<element tag="0002,0010" vr="UI" vm="1" len="22" name="TransferSyntaxUID">1.2.840.10008.1.2.4.70</element>
<element tag="0002,0012" vr="UI" vm="1" len="28" name="ImplementationClassUID">1.2.826.0.1.3680043.8.1055.1</element>
<element tag="0002,0013" vr="SH" vm="1" len="16" name="ImplementationVersionName">dicomlibrary-100</element>
<element tag="0002,0016" vr="AE" vm="1" len="12" name="SourceApplicationEntityTitle">DICOMLIBRARY</element>
</meta-header>
<data-set xfer="1.2.840.10008.1.2.4.70" name="JPEG Lossless, Non-hierarchical, 1st Order Prediction">
<element tag="0008,0005" vr="CS" vm="1" len="10" name="SpecificCharacterSet">ISO_IR 100</element>
<element tag="0008,0008" vr="CS" vm="3" len="22" name="ImageType">ORIGINAL\PRIMARY\OTHER</element>
<element tag="0008,0012" vr="DA" vm="1" len="8" name="InstanceCreationDate">20070101</element>
<element tag="0008,0013" vr="TM" vm="1" len="14" name="InstanceCreationTime">120000.000000</element>......

</data-set>
</file-format>
```
I am getting
```
CREATE  TABLE images_table (imageType String, instanceCreationDate STRING)
ROW FORMAT SERDE 'com.ibm.spss.hive.serde2.xml.XmlSerDe'
WITH SERDEPROPERTIES (
"column.xpath.imageType"="/data-set/element/ImageType",
"column.xpath.instanceCreationDate"="/data-set/element/InstanceCreationDate"
)
STORED AS
INPUTFORMAT 'com.ibm.spss.hive.serde2.xml.XmlInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat'
LOCATION '/Users/hadoop/Documents/dcm-images/series-000001'
TBLPROPERTIES (
"xmlinput.start"="<file-format>",
"xmlinput.end"="</file-format>"
)
```
Time taken: 0.351 seconds
17/06/16 11:06:09 [main]: INFO CliDriver: Time taken: 0.351 seconds
17/06/16 11:06:09 [main]: INFO log.PerfLogger: <PERFLOG method=releaseLocks from=org.apache.hadoop.hive.ql.Driver>
17/06/16 11:06:09 [main]: INFO log.PerfLogger: </PERFLOG method=releaseLocks start=1497636369523 end=1497636369523 duration=0 from=org.apache.hadoop.hive.ql.Driver>
17/06/16 11:06:09 [main]: DEBUG session.SessionState: Removing resource dir /Users/**/apache-hive-1.2.2-bin/iotmp
17/06/16 11:06:09 [IPC Parameter Sending Thread #0]: DEBUG ipc.Client: IPC Client (36883680) connection to localhost/127.0.0.1:9000 from hadoop sending #21
17/06/16 11:06:09 [IPC Client (36883680) connection to localhost/127.0.0.1:9000 from hadoop]: DEBUG ipc.Client: IPC Client (36883680) connection to localhost/127.0.0.1:9000 from hadoop got value #21
17/06/16 11:06:09 [main]: DEBUG ipc.ProtobufRpcEngine: Call: delete took 2ms
17/06/16 11:06:09 [IPC Parameter Sending Thread #0]: DEBUG ipc.Client: IPC Client (36883680) connection to localhost/127.0.0.1:9000 from hadoop sending #22
17/06/16 11:06:09 [IPC Client (36883680) connection to localhost/127.0.0.1:9000 from hadoop]: DEBUG ipc.Client: IPC Client (36883680) connection to localhost/127.0.0.1:9000 from hadoop got value #22
17/06/16 11:06:09 [pool-1-thread-1]: DEBUG ipc.ProtobufRpcEngine: Call: getFileInfo took 1ms
17/06/16 11:06:09 [IPC Parameter Sending Thread #0]: DEBUG ipc.Client: IPC Client (36883680) connection to localhost/127.0.0.1:9000 from hadoop sending #23
17/06/16 11:06:09 [IPC Client (36883680) connection to localhost/127.0.0.1:9000 from hadoop]: DEBUG ipc.Client: IPC Client (36883680) connection to localhost/127.0.0.1:9000 from hadoop got value #23
17/06/16 11:06:09 [pool-1-thread-1]: DEBUG ipc.ProtobufRpcEngine: Call: getFileInfo took 0ms
17/06/16 11:06:09 [pool-1-thread-1]: DEBUG ipc.Client: stopping client from cache: org.apache.hadoop.ipc.Client@1e54cb33
17/06/16 11:06:09 [pool-1-thread-1]: DEBUG ipc.Client: removing client from cache: org.apache.hadoop.ipc.Client@1e54cb33
17/06/16 11:06:09 [pool-1-thread-1]: DEBUG ipc.Client: stopping actual client because no more references remain: org.apache.hadoop.ipc.Client@1e54cb33
17/06/16 11:06:09 [pool-1-thread-1]: DEBUG ipc.Client: Stopping client
17/06/16 11:06:09 [IPC Client (36883680) connection to localhost/127.0.0.1:9000 from hadoop]: DEBUG ipc.Client: IPC Client (36883680) connection to localhost/127.0.0.1:9000 from hadoop: closed
17/06/16 11:06:09 [IPC Client (36883680) connection to localhost/127.0.0.1:9000 from hadoop]: DEBUG ipc.Client: IPC Client (36883680) connection to localhost/127.0.0.1:9000 from hadoop: stopped, remaining connections 0
17/06/16 11:06:09 [Thread-0]: DEBUG util.ShutdownHookManager: ShutdownHookManger complete shutdown.

The table gets created but no data is loaded. Any suggestions.

**Comment by dvasilen** [comment]
To get the image type and creation date I would use something like this 

```
DROP TABLE IF EXISTS xml_41;

CREATE  TABLE xml_41 (imap map<string,string>)
ROW FORMAT SERDE 'com.ibm.spss.hive.serde2.xml.XmlSerDe'
WITH SERDEPROPERTIES (
"column.xpath.imap"="/file-format/data-set/element",
"xml.map.specification.element"="@name->#content"
)
STORED AS
INPUTFORMAT 'com.ibm.spss.hive.serde2.xml.XmlInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat'
TBLPROPERTIES (
"xmlinput.start"="<file-format>",
"xmlinput.end"="</file-format>"
);


load data local inpath '/Users/dvasilen/Misc/XML/41.xml' OVERWRITE into table xml_41;

select  imap["ImageType"], imap["InstanceCreationDate"] from xml_41;
```

Here is the output:

```
    > select  imap["ImageType"], imap["InstanceCreationDate"] from xml_41;
OK
ORIGINAL\PRIMARY\OTHER	20070101
Time taken: 0.079 seconds, Fetched: 1 row(s)
```
