### ISSUE TITLE
Key/Value pair

### ISSUE THREAD

**Issue by paciferous** [dvasilen/Hive-XML-SerDe#47]
`<Search>`

    <Country>USA</Country>
    <Region>West</Region>
    <Address>
        <Home>
            <Item>
                    <id>Number</id>
                    <value>135</value>
                </Item>
            <Item>
                    <id>Street</id>
                    <value>Pacific</value>
                </Item>
            <Item>
                    <id>City</id>
                    <value>Irvine</value>
                </Item>
            </Home>
         <Home>
            <Item>
                    <id>Number</id>
                    <value>1672</value>
                </Item>
            <Item>
                    <id>Street</id>
                    <value>Madison</value>
                </Item>
            <Item>
                    <id>City</id>
                    <value>Denver</value>
                </Item>
             </Home>
         </Address>
</Search>

I am trying to create the below table structure but I am not getting the desired result 

Country    Region       Map
USA           West         {Number:135,Street:Pacific,City:Irvine}
USA           West         {Number:1672,Street:Madison,City:Denver}

`CREATE EXTERNAL TABLE search(
country string,
region string,
search array<struct<item:map<string,string>>>
  )
PARTITIONED BY(date STRING)
ROW FORMAT SERDE 'com.ibm.spss.hive.serde2.xml.XmlSerDe'
WITH SERDEPROPERTIES(
"column.xpath.country" = "/Search/country/text()",
"column.xpath.region" = "/Search/region/text()",
"column.xpath.item"="/Search/Address/Home/Item"
  )
STORED AS 
INPUTFORMAT 'com.ibm.spss.hive.serde2.xml.XmlInputFormat' 
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat' 
LOCATION '/search' 
TBLPROPERTIES (
"xmlinput.start"="<Search>",
"xmlinput.end"="</Search>"
);

Any help would be great. Thank you. `

**Comment by dvasilen** [comment]
See https://stackoverflow.com/questions/46118109/hive-xml-serde-key-value-pair-map/46125580#46125580

**Comment by paciferous** [comment]
I am able to get the data in this format 

USA WEST [NUMBER,Street,City] [135,Pacific,Irvine] 
USA WEST [NUMBER,Street,City] [1672,Madison,Denver]

However I am not able to map to the below format

USA WEST [NUMBER:135,Street:Pacific,City:Irvine] 
USA WEST [NUMBER:1672,Street:Madison,City:Denver]
