### ISSUE TITLE
Issue with xml node names containing a hyphen

### ISSUE THREAD

**Issue by rprodhom** [dvasilen/Hive-XML-SerDe#51]
Hi,

I have an issue linked with the STRUCT type in Hive. 
My xml file looks something like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<monitorEvent>
 <applicationData>
  <tracking-point>
   <tracked-field name="trackedField1" id="1" type="dateTime">date1</tracked-field>
   <tracked-field name="trackedField2" id="2" type="string">field1</tracked-field>
   <tracked-field name="trackedField3" id="3" type="string">field2</tracked-field>
   <tracked-field name="trackedField4" id="4" type="string">field3</tracked-field>
  </tracking-point>
 </applicationData>
</monitorEvent>
```

I would like to use this file as a source for the following table in Hive:

```
CREATE EXTERNAL TABLE IF NOT EXISTS table_xml (
dc_trackedfield ARRAY<STRUCT<id:STRING,name:STRING,type:STRING,tracked-field:STRING>>
)
ROW FORMAT SERDE 'com.ibm.spss.hive.serde2.xml.XmlSerDe'
WITH SERDEPROPERTIES (
"column.xpath.dc_trackedfield"="/monitorEvent/applicationData/tracking-point/tracked-field"
)
STORED AS
INPUTFORMAT 'com.ibm.spss.hive.serde2.xml.XmlInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat'
LOCATION 'hdfs:////tmp/table_xml'
TBLPROPERTIES (
"xmlinput.start"="<monitorEvent",
"xmlinput.end"="</monitorEvent>"
);
```

And the table should in the end contain 1 line that would look like this:
```
[{
		"id": "1",
		"name": "trackedField1",
		"type": "dateTime",
		"tracked-field": "date1"
	}, {
		"id": "2",
		"name": "trackedField2",
		"type": "string",
		"tracked-field": "field2"
	}, {
		"id": "3",
		"name": "trackedField3",
		"type": "string",
		"tracked-field": "field3"
	}, {
		"id": "4",
		"name": "trackedField4",
		"type": "string",
		"tracked-field": "field4"
	}
]
```

The problem is that in the STRUCT type in Hive, the field names cannot contain a hyphen, or the "-" character. I tried to create the table with the previous hql code, and I had the following hive error:

> MismatchedTokenException(304!=9)
> FAILED: ParseException line 2:70 mismatched input '-' expecting : near 'tracked' in column specification
> 

And without the hyphen in the "tracked-field" field, the automatic mapping of the xml file into the hive array does not work as the field name is different than the one in the xml file...

Do you have any idea if there would be a way to make this work without altering the source file?

Thank you for your help,

Romain

**Comment by dvasilen** [comment]
Hive does not support dash in the field name of a complex types, see https://issues.apache.org/jira/browse/HIVE-13748. So it seems that you will have to alter the XML to make it work.

**Comment by rprodhom** [comment]
ok thank you for your answer.
