### ISSUE TITLE
Not able to create table for JSON data using hive serde

### ISSUE THREAD

**Issue by debuggerrr** [dvasilen/Hive-XML-SerDe#57]
I want to load below JSON data and for that I am trying to create table as below:  

`CREATE TABLE my_table (field1 string, field2 int, field3 string, field4 double) ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe' ;`

I added below JAR files : 
```
1) hive-json-serde.jar
2) hive-json-serde-0.2.jar
3) json-serde-1.3.6-SNAPSHOT-jar-with-dependencies.jar
4) json-serde-1.3.jar 
```

but it gives me below error:  
`FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. Could not initialize class org.openx.data.jsonserde.objectinspector.JsonObjectInspectorFactory
`
I want to load below data:  
[{
	"field1": "data1",
	"field2": 100,
	"field3": "more data1",
	"field4": 123.001
}, {
	"field1": "data2",
	"field2": 200,
	"field3": "more data2",
	"field4": 123.002
}, {
	"field1": "data3",
	"field2": 300,
	"field3": "more data3",
	"field4": 123.003
}, {
	"field1": "data4",
	"field2": 400,
	"field3": "more data4",
	"field4": 123.004
}] 

I referred many links from stackoverflow as well as from github but of no use. Please help me with this. Let me know where I am going wrong.

**Comment by dvasilen** [comment]
@debuggerrr please create an issue at https://github.com/rcongiu/Hive-JSON-Serde
